// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'enums.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

const _$TokenSortEnumMap = {
  TokenSort.MARKET_CAP: 'market_cap',
  TokenSort.PERCENTAGE_PRICE_CHANGE: 'last_24_hour_change_percentage',
  TokenSort.TOTAL_LIQUIDITY: 'total_liquidity',
  TokenSort.COINGECKO_RANK: 'coingecko_rank',
};

const _$NFTItemSortEnumMap = {
  NFTItemSort.RANK: 'rank',
};

const _$ProtocolSortEnumMap = {
  ProtocolSort.NAME: 'protocol_name',
  ProtocolSort.TVL: 'total_tvl',
};

const _$NFTCollectionSortEnumMap = {
  NFTCollectionSort.VOLUME: 'volume',
  NFTCollectionSort.MARKET_CAP: 'market_cap',
  NFTCollectionSort.FLOOR_PRICE: 'floor_price',
  NFTCollectionSort.LAST_24H_PRICE_CHANGE: 'last_24h_change',
};

const _$TierKeysEnumMap = {
  TierKeys.ONE_DAY: '1d',
  TierKeys.ONE_WEEK: '7d',
  TierKeys.ONE_MONTH: '30d',
  TierKeys.ONE_YEAR: '365d',
};

const _$TimeseriesEventKeyEnumMap = {
  TimeseriesEventKey.NEW_TOKEN: 'NEW_TOKEN',
  TimeseriesEventKey.NEW_INTEGRATION: 'NEW_INTEGRATION',
  TimeseriesEventKey.PRICE_NOT_FOUND: 'PRICE_NOT_FOUND',
  TimeseriesEventKey.WALLET_CREATED: 'WALLET_CREATED_EVENT',
  TimeseriesEventKey.NEW_TOKEN_BALANCE_CHANGE: 'NEW_TOKEN_BALANCE_CHANGE',
  TimeseriesEventKey.NEW_INTEGRATION_BALANCE_CHANGE:
      'NEW_INTEGRATION_BALANCE_CHANGE',
};

const _$ChainKeysEnumMap = {
  ChainKeys.FIAT: 'FIAT',
  ChainKeys.BTC: 'BTC',
  ChainKeys.LTC: 'LTC',
  ChainKeys.BTC_CASH: 'BTC_CASH',
  ChainKeys.DOGECOIN: 'DOGECOIN',
  ChainKeys.NEAR: 'NEAR',
  ChainKeys.SOLANA: 'SOLANA',
  ChainKeys.CARDANO: 'CARDANO',
  ChainKeys.SORA: 'SORA',
  ChainKeys.IOTEX: 'IOTEX',
  ChainKeys.RONIN: 'RONIN',
  ChainKeys.TOMOCHAIN: 'TOMOCHAIN',
  ChainKeys.NYX: 'NYX',
  ChainKeys.DIG: 'DIG',
  ChainKeys.SEI: 'SEI',
  ChainKeys.ARKH: 'ARKH',
  ChainKeys.AIOZ: 'AIOZ',
  ChainKeys.JUNO: 'JUNO',
  ChainKeys.UMEE: 'UMEE',
  ChainKeys.IRIS: 'IRIS',
  ChainKeys.ODIN: 'ODIN',
  ChainKeys.MEME: 'MEME',
  ChainKeys.XPLA: 'XPLA',
  ChainKeys.MARS: 'MARS',
  ChainKeys.IDEP: 'IDEP',
  ChainKeys.OCTA: 'OCTA',
  ChainKeys.MAYA: 'MAYA',
  ChainKeys.AKASH: 'AKASH',
  ChainKeys.PLANQ: 'PLANQ',
  ChainKeys.REGEN: 'REGEN',
  ChainKeys.TERRA: 'TERRA',
  ChainKeys.CANTO: 'CANTO',
  ChainKeys.DYSON: 'DYSON',
  ChainKeys.LOGOS: 'LOGOS',
  ChainKeys.CUDOS: 'CUDOS',
  ChainKeys.CHEQD: 'CHEQD',
  ChainKeys.RIZON: 'RIZON',
  ChainKeys.ETHOS: 'ETHOS',
  ChainKeys.POINT: 'POINT',
  ChainKeys.NOMIC: 'NOMIC',
  ChainKeys.REBUS: 'REBUS',
  ChainKeys.ONOMY: 'ONOMY',
  ChainKeys.NOLUS: 'NOLUS',
  ChainKeys.LAMBDA: 'LAMBDA',
  ChainKeys.JACKAL: 'JACKAL',
  ChainKeys.STRIDE: 'STRIDE',
  ChainKeys.MYTHOS: 'MYTHOS',
  ChainKeys.BEEZEE: 'BEEZEE',
  ChainKeys.DESMOS: 'DESMOS',
  ChainKeys.COMDEX: 'COMDEX',
  ChainKeys.TGRADE: 'TGRADE',
  ChainKeys.GALAXY: 'GALAXY',
  ChainKeys.CARBON: 'CARBON',
  ChainKeys.LUMENX: 'LUMENX',
  ChainKeys.SHENTU: 'SHENTU',
  ChainKeys.AXELAR: 'AXELAR',
  ChainKeys.EMONEY: 'EMONEY',
  ChainKeys.TERRA2: 'TERRA2',
  ChainKeys.COSMOS: 'COSMOS',
  ChainKeys.SECRET: 'SECRET',
  ChainKeys.QUASAR: 'QUASAR',
  ChainKeys.KUJIRA: 'KUJIRA',
  ChainKeys.AGORIC: 'AGORIC',
  ChainKeys.ARCHWAY: 'ARCHWAY',
  ChainKeys.EIGHTBALL: '8BALL',
  ChainKeys.NEUTRON: 'NEUTRON',
  ChainKeys.MIGALOO: 'MIGALOO',
  ChainKeys.DECENTR: 'DECENTR',
  ChainKeys.VIDULUM: 'VIDULUM',
  ChainKeys.ECHELON: 'ECHELON',
  ChainKeys.GENESIS: 'GENESIS',
  ChainKeys.KICHAIN: 'KICHAIN',
  ChainKeys.PANACEA: 'PANACEA',
  ChainKeys.PASSAGE: 'PASSAGE',
  ChainKeys.BITSONG: 'BITSONG',
  ChainKeys.GRAVITY: 'GRAVITY',
  ChainKeys.BOSTROM: 'BOSTROM',
  ChainKeys.OSMOSIS: 'OSMOSIS',
  ChainKeys.STARGAZE: 'STARGAZE',
  ChainKeys.STARNAME: 'STARNAME',
  ChainKeys.SIFCHAIN: 'SIFCHAIN',
  ChainKeys.SENTINEL: 'SENTINEL',
  ChainKeys.LIKECOIN: 'LIKECOIN',
  ChainKeys.CRESCENT: 'CRESCENT',
  ChainKeys.CERBERUS: 'CERBERUS',
  ChainKeys.BITCANNA: 'BITCANNA',
  ChainKeys.TERITORI: 'TERITORI',
  ChainKeys.FETCHHUB: 'FETCHHUB',
  ChainKeys.IMVERSED: 'IMVERSED',
  ChainKeys.STAFIHUB: 'STAFIHUB',
  ChainKeys.BLUZELLE: 'BLUZELLE',
  ChainKeys.ACRECHAIN: 'ACRECHAIN',
  ChainKeys.OKEXCHAIN: 'OKEXCHAIN',
  ChainKeys.MICROTICK: 'MICROTICK',
  ChainKeys.BANDCHAIN: 'BANDCHAIN',
  ChainKeys.GENESISL1: 'GENESISL1',
  ChainKeys.ORAICHAIN: 'ORAICHAIN',
  ChainKeys.THORCHAIN: 'THORCHAIN',
  ChainKeys.SOMMELIER: 'SOMMELIER',
  ChainKeys.CHIHUAHUA: 'CHIHUAHUA',
  ChainKeys.INJECTIVE: 'INJECTIVE',
  ChainKeys.IMPACTHUB: 'IMPACTHUB',
  ChainKeys.CRYPTO_ORG: 'CRYPTO_ORG',
  ChainKeys.FIRMACHAIN: 'FIRMACHAIN',
  ChainKeys.PROVENANCE: 'PROVENANCE',
  ChainKeys.LUMNETWORK: 'LUMNETWORK',
  ChainKeys.QUICKSILVER: 'QUICKSILVER',
  ChainKeys.OMNIFLIXHUB: 'OMNIFLIXHUB',
  ChainKeys.ASSETMANTLE: 'ASSETMANTLE',
  ChainKeys.PERSISTENCE: 'PERSISTENCE',
  ChainKeys.KAVA_COSMOS: 'KAVA_COSMOS',
  ChainKeys.UNIFICATION: 'UNIFICATION',
  ChainKeys.SHARELEDGER: 'SHARELEDGER',
  ChainKeys.MEDASDIGITAL: 'MEDASDIGITAL',
  ChainKeys.EVMOS_COSMOS: 'EVMOS_COSMOS',
  ChainKeys.KONSTELLATION: 'KONSTELLATION',
  ChainKeys.CHRONICNETWORK: 'CHRONICNETWORK',
  ChainKeys.COMMERCIONETWORK: 'COMMERCIONETWORK',
  ChainKeys.BSC: 'BSC',
  ChainKeys.BOBA: 'BOBA',
  ChainKeys.CELO: 'CELO',
  ChainKeys.TRON: 'TRON',
  ChainKeys.HECO: 'HECO',
  ChainKeys.BASE: 'BASE',
  ChainKeys.OASIS: 'OASIS',
  ChainKeys.GNOSIS: 'GNOSIS',
  ChainKeys.ZKSYNC: 'ZKSYNC',
  ChainKeys.CRONOS: 'CRONOS',
  ChainKeys.KLAYTN: 'KLAYTN',
  ChainKeys.NERVOS: 'NERVOS',
  ChainKeys.AURORA: 'AURORA',
  ChainKeys.FANTOM: 'FANTOM',
  ChainKeys.HARMONY: 'HARMONY',
  ChainKeys.POLYGON: 'POLYGON',
  ChainKeys.ETHEREUM: 'ETHEREUM',
  ChainKeys.OPTIMISM: 'OPTIMISM',
  ChainKeys.ARBITRUM: 'ARBITRUM',
  ChainKeys.KAVA_EVM: 'KAVA_EVM',
  ChainKeys.MOONBEAM: 'MOONBEAM',
  ChainKeys.NERVOS_GW: 'NERVOS_GW',
  ChainKeys.EVMOS_EVM: 'EVMOS_EVM',
  ChainKeys.AVALANCHE: 'AVALANCHE',
  ChainKeys.MOONRIVER: 'MOONRIVER',
  ChainKeys.CANTO_EVM: 'CANTO_EVM',
  ChainKeys.INJECTIVE_EVM: 'INJECTIVE_EVM',
  ChainKeys.OKX: 'OKX',
  ChainKeys.GATE: 'GATE',
  ChainKeys.BYBIT: 'BYBIT',
  ChainKeys.KUCOIN: 'KUCOIN',
  ChainKeys.CRYPTO: 'CRYPTO',
  ChainKeys.KRAKEN: 'KRAKEN',
  ChainKeys.BINANCE: 'BINANCE',
  ChainKeys.COINBASE: 'COINBASE',
  ChainKeys.BNB_BEACON_CHAIN: 'BNB_BEACON_CHAIN',
  ChainKeys.AVALANCHE_P_CHAIN: 'AVALANCHE_P_CHAIN',
};

const _$TokenTypeEnumMap = {
  TokenType.ADDRESS: 'address',
  TokenType.NATIVE: 'native_token',
  TokenType.DENOM: 'denom',
};

const _$DebtTypeEnumMap = {
  DebtType.FARM: 'FARM',
  DebtType.LOAN: 'LOAN',
  DebtType.SHORT: 'SHORT',
  DebtType.MARGIN: 'MARGIN',
  DebtType.MARGIN_LONG: 'MARGIN_LONG',
  DebtType.MARGIN_SHORT: 'MARGIN_SHORT',
  DebtType.LEVERAGE_POSITION: 'LEVERAGE_POSITION',
};

const _$AnnualReturnTypeEnumMap = {
  AnnualReturnType.APY: 'APY',
  AnnualReturnType.APR: 'APR',
};

const _$OptionTypeEnumMap = {
  OptionType.LONG_PUT: 'LONG_PUT',
  OptionType.LONG_CALL: 'LONG_CALL',
  OptionType.SHORT_PUT: 'SHORT_PUT',
  OptionType.SHORT_CALL: 'SHORT_CALL',
};

const _$OrderTypeEnumMap = {
  OrderType.BUY: 'BUY',
  OrderType.SELL: 'SELL',
};
